var chatApp=angular.module('chatApp',['ngRoute','ngMaterial'])
  .config(function($routeProvider){
    $routeProvider
    .when('/login',{
      templateUrl:'views/login.html',
      controller:'LoginController'
    })
    .when('/register',{
      templateUrl:'views/register.html',
      controller:'RegisterController'
    })
    .when('/chat',{
      templateUrl:'views/chat.html',
      controller:'ChatController'
    })
    .otherwise({
      redirectTo:'/'
    });
});
